#!/bin/sh -e

targets="$@"
if [ "$targets" = "" ]; then
        targets="all test"
fi

#platform=`uname -sm| sed 's/  */-/g'`
platform=`config/config.guess`
srcdir=`pwd`

if [ "$BUILDNAME" = "" ]; then
	builddir="build/$platform"
else
	builddir="build/$BUILDNAME-$platform"
fi

if [ -d /sw/bin ]; then
	# Have to use fink autoconf/libtool or build dies
	PATH=/sw/bin:${PATH} 
	export PATH
fi

build() {
	msg="Checking for $builddir/Makefile..."
	if [ \! -f $builddir/Makefile ]; then
		echo "$msg creating with configure"
		mkdir -p $builddir
		cd $builddir
		$srcdir/configure --srcdir=$srcdir $CONFIG
	else 
		echo "$msg exists"
		cd $builddir
	fi
	
	echo "Building in $builddir"
	make $targets
}

build && ln -sf $builddir/bin/smacqq
