#!/bin/sh

targets="$@"
if [ "$targets" = "" ]; then
        targets="all test"
fi

platform=`uname -sm| sed 's/  */-/g'`
srcdir=`pwd`
builddir="build/$platform"

build() {

	echo "Checking for $builddir/Makefile"
	if [ \! -f $builddir/Makefile ]; then
		mkdir -p $builddir
		cd $builddir
		$srcdir/configure --srcdir=$srcdir $CONFIG
	else 
		cd $builddir
	fi
	
	echo "Building in $builddir"
	make $targets
}

(build)
ln -sf $builddir/bin/smacqq
