#!/bin/sh

has() {
	which "$1" > /dev/null 2>&1
}

config() {
	LIBTOOL=${LIBTOOL:-libtool}
	USR=${USR:-/usr}
	LDXX=${LDXX:-g++}

	if [ `uname -s` = "Darwin" ]; then 
		echo 'MAKE=gnumake'
		LIBTOOL=glibtool
		LDOPTS="${LDOPTS}-L/sw/lib -ldl"
		COPTS="${COPTS}-I/sw/include "
		USR="/sw/"

	elif [ `uname -s` = "FreeBSD" ]; then
		echo 'MAKE=gmake'
		USR="/usr/local/"
		LDOPTS="${LDOPTS}-L/usr/local/lib -liconv -lintl"
		echo 'M4=gm4'

	elif [ `uname -s` = "Linux" ]; then
		# Red Hat 8.0: 
		if has g++296; then 
			LDXX="--mode=link g++296"
			echo 'CXX=--mode=compile g++296'
		fi 
		if has gcc296; then 
			echo 'CC=gcc296'
		fi 

		# Red Hat 7.3: 
		if [ -d /usr/include/pcap ]; then 
			COPTS="${COPTS}-I/usr/include/pcap "
		fi 
		LDOPTS="${LDOPTS}-ldl"
		
	fi 
	#export MAKE COPTS LIBTOOL LDOPTS CC CXX 

	PWD=`pwd`

	echo "LIBTOOL=$LIBTOOL"
	echo "LDXX=$LDXX"
	echo "USR=$USR"
	echo "LDOPTS=$LDOPTS"
	#echo "COPTS=$COPTS"
	echo "CFLAGS=$COPTS"
	echo "MAKEINCLUDES=$PWD/misc/include.mk"
	echo "TOPSRCDIR=${TOPSRCDIR:-$PWD}"
	echo "SRCDIR=$PWD"
	echo "VPATH=$PWD"
	echo "TOPBINDIR=${TOPBINDIR:-$PWD/build/$platform}"
	echo "BINDIR=$PWD/build/$platform"
	echo "include $PWD/misc/include.mk"
}

platform=`uname -sm| sed 's/  */-/g'`
mkdir -p build/$platform
config > build/$platform/config.mk
