#!/bin/sh

has() {
	which "$1" > /dev/null 2>&1
}

config() {
	LIBTOOL=${LIBTOOL:-libtool}
	USR=${USR:-/usr}
	LDXX=${LDXX:-g++}
	DOCBOOK2MAN=${DOCBOOK2MAN:-docbook-to-man}

	if [ `uname -s` = "Darwin" ]; then 
		echo 'MAKE=gnumake'
		LIBTOOL=glibtool
		LDOPTS="${LDOPTS}-L/lib -L/usr/lib -L/sw/lib -ldl"
		COPTS="${COPTS}-I/usr/include -I/sw/include "
		USR="/sw/"

	elif [ `uname -s` = "FreeBSD" ]; then
		echo 'MAKE=gmake'
		USR="/usr/local/"
		LDOPTS="${LDOPTS}-L/usr/local/lib -liconv -lintl"
		echo 'M4=gm4'

	elif [ `uname -s` = "Linux" ]; then
		# Red Hat 8.0: 
		if has g++296; then 
			LDXX="--mode=link g++296"
			echo 'CXX=--mode=compile g++296'
		fi 
		if has gcc296; then 
			echo 'CC=gcc296'
		fi 

		if has gcc-3.3; then
			if has gcc-3.2; then
				echo 'Using gcc-3.2 instead of 3.3' >&2
				echo 'CC=gcc-3.2'
			else 
				echo 'Cannot use gcc 3.3' >&2
				exit 1
			fi
		fi

		# Red Hat 7.3: 
		if [ -d /usr/include/pcap ]; then 
			COPTS="${COPTS}-I/usr/include/pcap "
		fi 

		# Red Hat:
		if [ \! -f /usr/bin/docbook-to-man -a -f /usr/bin/docbook2man ]; then
			DOCBOOK2MAN=docbook2man
		fi

		LDOPTS="${LDOPTS}-ldl"
		
	fi 
	#export MAKE COPTS LIBTOOL LDOPTS CC CXX 

	PWD=`pwd`

	echo "DOCBOOK2MAN=$DOCBOOK2MAN"
	echo "LIBTOOL=$LIBTOOL"
	echo "LDXX=$LDXX"
	echo "USR=$USR"
	echo "LDOPTS=$LDOPTS"
	#echo "COPTS=$COPTS"
	echo "COPTS=$COPTS"
	echo "MAKEINCLUDES=$PWD/misc/include.mk"
	echo "TOPSRCDIR=${TOPSRCDIR:-$PWD}"
	echo "SRCDIR=$PWD"
	echo "VPATH=$PWD"
	echo "TOPBINDIR=${TOPBINDIR:-$PWD/build/$platform}"
	echo "BINDIR=$PWD/build/$platform"
	echo "include $PWD/misc/include.mk"
}

platform=`uname -sm| sed 's/  */-/g'`
mkdir -p build/$platform
config > build/$platform/config.mk
