#!/bin/sh

dirs="/usr/lib"

for word in "$@"; do
	case $word in
		-lc|-lpthread|-ldl)
			;;
		-l*)
			lib=`echo "$word" | sed 's/^-l/lib/'`
			for d in $dirs; do 
				if [ -r $d/${lib}.a ]; then
					# Replace -l argument with explicit .a file
					word="$d/${lib}.a"
				fi
			done
			;;
		-L*)
			dir=`echo "$word" | sed 's/^-L//'`
			dirs="$dir $dirs"
			;;
	esac

	args="$args$word "
done

echo "$args"
$args
