#!/bin/sh  -e

DSTDIR="$TOPSRCDIR/build/iso/"
REPOSITORY=:pserver:anonymous@cvs.sourceforge.net:/cvsroot/smacq

rm -Rf "$DSTDIR"
mkdir -p "$DSTDIR/doc/"
mkdir -p "$DSTDIR/.bin/"

cd $TOPSRCDIR

	cp misc/smacq.ico misc/autorun.inf "$DSTDIR"
	cp doc/*.txt doc/*.pdf "$DSTDIR/doc/"
	platforms=`cd build; echo *-*`

	for p in $platforms; do
		mkdir "$DSTDIR/.bin/$p"
		cp "build/$p/bin/smacqq" "$DSTDIR/.bin/$p/"
	done	

	echo "$REPOSITORY A" > /tmp/cvs.$$
	(cd "$DSTDIR"; CVS_PASSFILE=/tmp/cvs.$$ cvs -q -d $REPOSITORY co -P smacq; mv smacq src)
	rm /tmp/cvs.$$
	cp misc/reloc "$DSTDIR/.bin"
	(cd "$DSTDIR"; ln -f .bin/reloc smacqq)

	cp -rpf misc/SMACQ.app "$DSTDIR/" #For MacOS
	cp build/Darwin-Power-Macintosh/bin/smacqq "$DSTDIR/SMACQ.app/Contents/Resources/"

	# -hidden removes from Unix and requires /A on DOS, but shows on MacOS
	# -hide-joliet only hides from DOS/MacOSX
	mkisofs -hfs -hide-joliet '.*' -hide-hfs autorun.inf -hidden 'autorun.inf' -hide-hfs '*.ico'  -hide-joliet SMACQ.app -hide SMACQ.app -hidden '*.ico' -V SMACQ -hfs-volid "SMACQ for Mac" -R "$DSTDIR" > smacq.iso
	# --osx-double
