#!/bin/sh  -e

DSTDIR="$TOPSRCDIR/build/iso/"
REPOSITORY=:pserver:anonymous@cvs.sourceforge.net:/cvsroot/smacq

rm -Rf "$DSTDIR"
mkdir -p "$DSTDIR/doc/"
mkdir -p "$DSTDIR/.bin"

cd $TOPSRCDIR

Get_CVS() {
	echo "$REPOSITORY A" > /tmp/cvs.$$
	(cd "$DSTDIR"; CVS_PASSFILE=/tmp/cvs.$$ cvs -q -d $REPOSITORY co -P smacq; mv smacq src)
	rm /tmp/cvs.$$
}

MacApp() {
	cp -rpf misc/SMACQ.app "$DSTDIR/" #For MacOS
	mkdir -p "$DSTDIR/SMACQ.app/Contents/Resources/.bin/Darwin-Power-Macintosh/"
	(cd "$DSTDIR" && ln .bin/Darwin-Power-Macintosh/* "SMACQ.app/Contents/Resources/.bin/Darwin-Power-Macintosh/")
	(cd "$DSTDIR" && ln smacqq "SMACQ.app/Contents/Resources/smacqq")
}


	cp misc/smacq.ico misc/autorun.inf "$DSTDIR"
	cp doc/*.txt doc/*.pdf "$DSTDIR/doc/"
	platforms=`cd build; echo *-*`

	set -x
	for p in $platforms; do
		cp "build/$p/reloc/*" $DEPS "$DSTDIR/.bin/$p/"
	done	
	
	cp misc/reloc "$DSTDIR/.bin"
	(cd "$DSTDIR"; ln -f .bin/reloc smacqq)

	Get_CVS
	MacApp

	# -hidden removes from Unix and requires /A on DOS, but shows on MacOS
	# -hide-joliet only hides from DOS/MacOSX
	mkisofs -hfs -hide-joliet '.*' -hide-hfs autorun.inf -hidden 'autorun.inf' -hide-hfs '*.ico'  -hide-joliet SMACQ.app -hide SMACQ.app -hidden '*.ico' -V SMACQ -hfs-volid "SMACQ for Mac" -R "$DSTDIR" > smacq.iso
	# --osx-double
