#!/bin/sh -x

	rm -Rf build/iso
	mkdir -p build/iso/doc/
	mkdir -p build/iso/.bin/

	cp misc/smacq.ico misc/autorun.inf build/iso/
	cp doc/*.pdf build/iso/doc/
	cp $BINDIR/bin/smacqq misc/reloc build/iso/.bin
	(cd build/iso; ln -f .bin/reloc smacqq)

	cp -rpf misc/SMACQ.app build/iso/ #For MacOS
	cp $BINDIR/bin/smacqq build/iso/SMACQ.app/Contents/Resources/

	# -hidden removes from Unix and requires /A on DOS, but shows on MacOS
	# -hide-joliet only hides from DOS/MacOSX
	mkisofs -hfs -hide-joliet '.*' -hide-hfs autorun.inf -hidden 'autorun.inf' -hide-hfs '*.ico' -hide-hfs 'smacqq' -hidden SMACQ.app -hidden '*.ico' -V SMACQ -hfs-volid "SMACQ for Mac" --osx-double -R build/iso > smacq.iso
