#!/bin/sh

echo "#ifndef SMACQ_PRELOADS"
echo "#define SMACQ_PRELOADS"

syms=`cat`
for s in $syms; do
	echo "extern void * $s;"
done
echo "struct preload_entry preloads[] = {"
for s in $syms; do
	echo "  {&${s}, \"$s\"},"
done
echo "  {NULL, NULL}"
echo "};"
echo "#endif"
