#!/bin/sh 

basetest=`basename $1`
test=`basename $1`

out=$srcdir/$basetest.out 
run=`basename $basetest`.run 
err=`basename $basetest`.err

export TEST=$srcdir

(set -e; ${TOP_SRCDIR}/test/$test) > $run 2>$err
diff -U3 $out $run; 
stat="$?"
if [ "$stat" != "0" ]; then 
	echo "======== Errors from $basetest: ========"
	cat $err
	#echo "======== End of errors from $basetest ========"
	exit $stat
fi
