#!/bin/sh
DB=test
LFAP=/n/lfap/flows
MYSQLDIR=/var/lib/mysql/test
TEMPTABLE=tempips
HIST=/home/mfisk/hist
SCHEMA="rip int unsigned not null, sip int unsigned not null, dip int unsigned not null, input smallint unsigned not null, output smallint unsigned not null, srcport smallint unsigned not null, dstport smallint unsigned not null, packets int unsigned not null, bytes int unsigned not null, nip int unsigned not null, start timestamp not null, end timestamp not null, ipprotocol tinyint unsigned not null, mtime timestamp not null"
INDICES="INDEX sip (sip), INDEX dip (dip), INDEX start (start), INDEX end (end), INDEX srcport (srcport), INDEX dstport (dstport)"

gen_file() {
  smacqq "print(--mysql -f '$MYSQLDIR/${TEMPTABLE}.MYD' \
                        router \
                         srcip \
                         dstip \
                         input.ushort \
                        output.ushort \
                       srcport.ushort \
                       dstport.ushort \
                       packets.uint32 \
                         bytes.uint32 \
                       nexthop \
                         start.time \
                           end.time \
                    ipprotocol \
		      now.time
	) $2 from cflow('$1')"
}

load_all() {
  for f in $LFAP/flows.2005051*; do
	b=`basename $f`
	if [ ! -f $HIST/$b ]; then
		ts=`echo $b | perl -p -e 's/^flows.//; s/^(\d\d\d\d)(\d\d)(\d\d)_/$1-$2-$3 /; s/-0[0-9]00\.?g?z?$//'`
		echo time gen_file $f "const(-t timeval -f now '$ts')"
		time gen_file $f "const(-t timeval -f now '$ts')" && touch $HIST/$b
	fi
  done
}

move_into() {
	echo Moving data from $TEMPTABLE to $1 ....
	time mysql <<EOM
use $DB;
create table if not exists $1 ($SCHEMA, $INDICES);
flush table $TEMPTABLE;
insert into $1 select * from $TEMPTABLE;
truncate table $TEMPTABLE;
flush table $TEMPTABLE;
EOM
}

load_batch() {
	rm -f $MYSQLDIR/${TEMPTABLE}.*
	mysql <<EOM
		use $DB;
		create table $TEMPTABLE ($SCHEMA) ROW_FORMAT=FIXED ENGINE=MyISAM;
		flush table $TEMPTABLE;
EOM
	while true; do
		#ls -l $MYSQLDIR/${TEMPTABLE}.MYD
		gen_file - "from now() from head(100000)"
		#ls -l $MYSQLDIR/${TEMPTABLE}.MYD
		mysqlcheck -ossr $DB ${TEMPTABLE}
		#ls -l $MYSQLDIR/${TEMPTABLE}.MYD
		chown mysql $MYSQLDIR/${TEMPTABLE}.*
		move_into `date +"lfap_%Y_%m_%d"`
	done
}

load_continuous() {
	tail -c 10000000000000 -F $LFAP/flows.current | load_batch
}

load_continuous
