#!/usr/bin/perl

sub notany($resultstr, $arg) {
  local($resultstr, $arg) = @_;

  if ($arg eq 'any') { return; }
  
  $resultstr =~ s|ARG|$arg|g;

  push(@tests, $resultstr);
}

sub hex2octalstr() {
  local($hex) = @_;
  $res = '';

  while($hex) {
    if (! ($hex =~ /^(..) *(.*)$/)) { return $res; }
    $res .= '\\x' . $1;
    $hex = $2;
  }

  return $res;
}

if ($ARGV[0] eq "-p") {
	shift(@ARGV);
	$prob = $ARGV[0];
	shift(@ARGV);
} else {
	$prob = 1;
}

open(SNORT, ">/tmp/snortcq.conf") || die;
while(<>) {
  chomp;
  s|\$EXTERNAL_NET|!\$HOME_NET|g;
  s|\$HOME_NET|192.168.0.0/16|g;
  s|\$HTTP_SERVERS|any|g;
  s|\$SQL_SERVERS|any|g;
  s|\$HTTP_PORTS|80|g;
  s|\$ORACLE_PORTS|any|g;
  s|\$SMTP|any|g;

  ($action,$proto,$srcip,$srcport,$dir,$dstip,$dstport,$criteria) = split(/\s+/, $_, 8);
  
  if ($action ne "alert") { next; }

  #This is a rule, but do we want it?
  if (rand() > $prob) { next; }

  @tests = ();

  if ($proto ne "ip") {
  	&notany("ipprotocol = 'ARG'", $proto);
  }

  $srcip =~ s|\[([^,]+),.*\]|$1|;
  $dstip =~ s|\[([^,]+),.*\]|$1|;

  &notany("mask(srcip, 'ARG')", $srcip);
  &notany("mask(dstip, 'ARG')", $dstip);
  &notany("srcport = 'ARG'", $srcport);
  &notany("dstport = 'ARG'", $dstport);
  
  #print "Splitting $criteria\n";
  $criteria =~ s|^\(\s*||;
  $criteria =~ s|\s*\)\s*$||;

  # Split on unescaped semicolons
  $criteria =~ s|([^\\]);|$1 ;|g;
  @crits = split(/[^\\];/, $criteria);
  
  $content = '';
  $sid = '0';
  $snortrule = "alert $proto $srcip $srcport -> $dstip $dstport (";

  foreach $test (@crits) {
    $test =~ s|^\s+||;
    $test =~ s|\s+$||;

    ($op,$arg) = split(/\s*:\s*/, $test, 2);
    $arg =~ s|^\"||;
    $arg =~ s|\"$||;
    if ($op eq "sid") { 
      $sid = $arg; 
      $snortrule .= "sid:$sid; ";
    } elsif ($op eq "dsize") {
      if ($arg =~ /^([<>=]+)(.*)$/) {
      	$op = $1;
	$arg = $2;
      }  else {
      	$op = "=";
      }
      #&notany("payloadsize $op 'ARG'", $arg);
      #$snortrule .= "dsize:$arg; ";
    } elsif (($op eq "content") || ($op eq "uricontent")) { 
      if ($arg =~ /^!/) { next; }

      $parsedcontent = $arg; 
      $parsedcontent =~ s/\|([^|]*)\|/&hex2octalstr($1)/eg;
      &notany("substr(payload, \"ARG\")", $parsedcontent);

      $snortrule .= "content:\"$arg\"; ";
    } elsif ($op eq "msg" || $op eq "reference" || $op eq "classtype" || $op eq "rev" || $op eq "depth" || $op eq "nocase") {
      
    } else {
      print stderr "$_: [$op:$arg]\n";
    }
  }

  $q = "print sid, srcip, dstip, ts from (const('$sid', sid) from pcapfile(/hog/traces/aa.80)";
  if (@tests) {
  	$q .= " where ";
  	$q .= join(' and ', @tests);
  }

  print "$q)\n";

  print SNORT "$snortrule msg:\"$sid\"; )\n";
}
	  
