#!/bin/sh

PATH=${PATH}:.:bin/
file=$1
datafile=`echo $file | sed 's/.[^.]*$//'`.data

shift

fields="-d, ; , id, bytes, packets, srcip, srcport, prompta, broken, promptb, dstport, dstip:ip, packetsback, bytesback, date, start, finish"
pfields=`echo "$fields" | sed 's/:[a-z]*//g'`

#smacqq "print $pfields from tabularinput(-f,$file,$fields)" "$@"
smacqq "print $pfields,data.data from (ndjoin id, id, data, 'tabularinput(-f,$datafile,-d,;,id,data)' from tabularinput(-f,$file,$fields)" "$@" ")"

