.TH bytehash 3 "$Date: 2003/10/23 23:02:05 $" "LANL"
.SH NAME
bytehash - iovec hash table
.SH SYNOPSIS
.nf
.B #include <bytehash.h>
.fi

.TP
.BI "struct iovec_hash * bytes_hash_table_new(int maxkeybytes, int flags)"

Flags can include CHAIN, NOCHAIN, FREE, NOFREE.  The default is CHAIN|NOFREE.

.TP
.BI "int bytes_hash_table_incrementv(struct iovec_hash * ht, struct iovec *, int count)"
.TP
.BI "int bytes_hash_table_setv(struct iovec_hash * ht, struct iovec *, int count,  gpointer value)"
.TP
.BI "gpointer bytes_hash_table_setv(struct iovec_hash * ht, struct iovec * keys, int count, gpointer value)"
.TP
.BI "gpointer bytes_hash_table_lookupv(struct iovec_hash * ht, struct iovec *, int)"
.TP
.BI "int bytes_hash_table_removev(struct iovec_hash * ht, struct iovec *, int)"
.TP
.BI "void bytes_hash_table_destroy(struct iovec_hash * ht)"
.TP
.BI "gint bytes_hash_table_getv(struct iovec_hash * ht, struct iovec * key, int keys, gpointer *oldkey, gpointer *current)"
.TP
.BI "void bytes_init_hash(guint32** randoms, int num, unsigned long prime)"

.TP
.BI "guint32 bytes_hashv(struct iovec *, int nvecs)"
.TP
.BI "void bytes_hash_table_foreach(struct iovec_hash * ht, GHFunc func, gpointer user_data)"
.TP
.BI "void bytes_hash_table_foreach_remove(struct iovec_hash * ht, GHRFunc func, gpointer user_data)"

.SH "SEE ALSO"
.BR smacq(1),
.BR dts(3)

